# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/class/mipscpu/mipscpu_sim/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/class/mipscpu/mipscpu_sim/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/class/mipscpu/mipscpu_sim/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/class/mipscpu/mipscpu_sim/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
