# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/source/Nexys4DDR_CPU.xdc

# IP: ip/dmem/dmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmem || ORIG_REF_NAME==dmem} -quiet] -quiet
